---
name: 'Get changed files'
description: 'Get the changed files in a pull request or other event'
author: bjw-s-labs

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-pull-request
  color: orange

# Define your inputs here.
inputs:
  path:
    description: 'Base path to start searching from'
    required: false
    default: ''
  patterns:
    description: 'Glob patterns to match results against'
    required: false
    default: ''
  include_deleted_files:
    description: 'Whether to include only deleted files in the results'
    required: false
    default: 'false'
  include_only_directories:
    description: 'Whether to include only directories in the result'
    required: false
    default: 'false'
  max_depth:
    description: 'Maximum directory depth'
    required: false
    default: '0'
  token:
    description: 'GitHub token for authentication'
    default: ${{ github.token }}
    required: false

# Define your outputs here.
outputs:
  changed_files:
    description: JSON array of changed files

runs:
  using: node20
  main: dist/index.js
