---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: ${{ forgejo.ref }}-${{ forgejo.workflow }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Get changed files
        id: changed-files
        uses: ./
        with:
          patterns: |-
            .forgejo/workflows/*.yaml
            .forgejo/workflows/*.yml

      - name: Run actionlint
        if: steps.changed-files.outputs.changed_files && steps.changed-files.outputs.changed_files != '[]'
        uses: https://github.com/bjw-s-labs/action-actionlint@b346813e82708106544f48a93a5b3fbeeb8e37eb # v0.1.1
        with:
          actionlint_config: .forgejo/actionlint.yaml
          file_pattern: ${{ join(fromJSON(steps.changed-files.outputs.changed_files || '[]'), ' ') }}

  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        id: npm-ci
        run: |
          pnpm run ci

      - name: Run ESLint
        id: npm-lint
        run: pnpm run lint

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        id: npm-ci
        run: |
          pnpm run ci

      - name: Run prettier
        id: npm-format-check
        run: pnpm run format:check
